# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sibi/sandbox/ar_track_service

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sibi/sandbox/ar_track_service

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sibi/sandbox/ar_track_service/CMakeFiles /home/sibi/sandbox/ar_track_service/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sibi/sandbox/ar_track_service/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_cpp

# Build rule for target.
ROSBUILD_genmsg_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_cpp
.PHONY : ROSBUILD_genmsg_cpp

# fast build rule for target.
ROSBUILD_genmsg_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_cpp.dir/build.make CMakeFiles/ROSBUILD_genmsg_cpp.dir/build
.PHONY : ROSBUILD_genmsg_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_lisp

# Build rule for target.
ROSBUILD_genmsg_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_lisp
.PHONY : ROSBUILD_genmsg_lisp

# fast build rule for target.
ROSBUILD_genmsg_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_lisp.dir/build.make CMakeFiles/ROSBUILD_genmsg_lisp.dir/build
.PHONY : ROSBUILD_genmsg_lisp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_cpp

# Build rule for target.
ROSBUILD_gensrv_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_cpp
.PHONY : ROSBUILD_gensrv_cpp

# fast build rule for target.
ROSBUILD_gensrv_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_cpp.dir/build.make CMakeFiles/ROSBUILD_gensrv_cpp.dir/build
.PHONY : ROSBUILD_gensrv_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_lisp

# Build rule for target.
ROSBUILD_gensrv_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_lisp
.PHONY : ROSBUILD_gensrv_lisp

# fast build rule for target.
ROSBUILD_gensrv_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_lisp.dir/build.make CMakeFiles/ROSBUILD_gensrv_lisp.dir/build
.PHONY : ROSBUILD_gensrv_lisp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_py

# Build rule for target.
ROSBUILD_gensrv_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_py
.PHONY : ROSBUILD_gensrv_py

# fast build rule for target.
ROSBUILD_gensrv_py/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_py.dir/build.make CMakeFiles/ROSBUILD_gensrv_py.dir/build
.PHONY : ROSBUILD_gensrv_py/fast

#=============================================================================
# Target rules for targets named clean-test-results

# Build rule for target.
clean-test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-test-results
.PHONY : clean-test-results

# fast build rule for target.
clean-test-results/fast:
	$(MAKE) -f CMakeFiles/clean-test-results.dir/build.make CMakeFiles/clean-test-results.dir/build
.PHONY : clean-test-results/fast

#=============================================================================
# Target rules for targets named marker_image_service

# Build rule for target.
marker_image_service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 marker_image_service
.PHONY : marker_image_service

# fast build rule for target.
marker_image_service/fast:
	$(MAKE) -f CMakeFiles/marker_image_service.dir/build.make CMakeFiles/marker_image_service.dir/build
.PHONY : marker_image_service/fast

#=============================================================================
# Target rules for targets named marker_node

# Build rule for target.
marker_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 marker_node
.PHONY : marker_node

# fast build rule for target.
marker_node/fast:
	$(MAKE) -f CMakeFiles/marker_node.dir/build.make CMakeFiles/marker_node.dir/build
.PHONY : marker_node/fast

#=============================================================================
# Target rules for targets named marker_node_camera

# Build rule for target.
marker_node_camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 marker_node_camera
.PHONY : marker_node_camera

# fast build rule for target.
marker_node_camera/fast:
	$(MAKE) -f CMakeFiles/marker_node_camera.dir/build.make CMakeFiles/marker_node_camera.dir/build
.PHONY : marker_node_camera/fast

#=============================================================================
# Target rules for targets named marker_node_no_depth

# Build rule for target.
marker_node_no_depth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 marker_node_no_depth
.PHONY : marker_node_no_depth

# fast build rule for target.
marker_node_no_depth/fast:
	$(MAKE) -f CMakeFiles/marker_node_no_depth.dir/build.make CMakeFiles/marker_node_no_depth.dir/build
.PHONY : marker_node_no_depth/fast

#=============================================================================
# Target rules for targets named marker_service

# Build rule for target.
marker_service: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 marker_service
.PHONY : marker_service

# fast build rule for target.
marker_service/fast:
	$(MAKE) -f CMakeFiles/marker_service.dir/build.make CMakeFiles/marker_service.dir/build
.PHONY : marker_service/fast

#=============================================================================
# Target rules for targets named rosbuild_precompile

# Build rule for target.
rosbuild_precompile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_precompile
.PHONY : rosbuild_precompile

# fast build rule for target.
rosbuild_precompile/fast:
	$(MAKE) -f CMakeFiles/rosbuild_precompile.dir/build.make CMakeFiles/rosbuild_precompile.dir/build
.PHONY : rosbuild_precompile/fast

#=============================================================================
# Target rules for targets named rosbuild_premsgsrvgen

# Build rule for target.
rosbuild_premsgsrvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_premsgsrvgen
.PHONY : rosbuild_premsgsrvgen

# fast build rule for target.
rosbuild_premsgsrvgen/fast:
	$(MAKE) -f CMakeFiles/rosbuild_premsgsrvgen.dir/build.make CMakeFiles/rosbuild_premsgsrvgen.dir/build
.PHONY : rosbuild_premsgsrvgen/fast

#=============================================================================
# Target rules for targets named rospack_genmsg

# Build rule for target.
rospack_genmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg
.PHONY : rospack_genmsg

# fast build rule for target.
rospack_genmsg/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg.dir/build.make CMakeFiles/rospack_genmsg.dir/build
.PHONY : rospack_genmsg/fast

#=============================================================================
# Target rules for targets named rospack_genmsg_libexe

# Build rule for target.
rospack_genmsg_libexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg_libexe
.PHONY : rospack_genmsg_libexe

# fast build rule for target.
rospack_genmsg_libexe/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg_libexe.dir/build.make CMakeFiles/rospack_genmsg_libexe.dir/build
.PHONY : rospack_genmsg_libexe/fast

#=============================================================================
# Target rules for targets named rospack_gensrv

# Build rule for target.
rospack_gensrv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_gensrv
.PHONY : rospack_gensrv

# fast build rule for target.
rospack_gensrv/fast:
	$(MAKE) -f CMakeFiles/rospack_gensrv.dir/build.make CMakeFiles/rospack_gensrv.dir/build
.PHONY : rospack_gensrv/fast

#=============================================================================
# Target rules for targets named rospack_gensrv_all

# Build rule for target.
rospack_gensrv_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_gensrv_all
.PHONY : rospack_gensrv_all

# fast build rule for target.
rospack_gensrv_all/fast:
	$(MAKE) -f CMakeFiles/rospack_gensrv_all.dir/build.make CMakeFiles/rospack_gensrv_all.dir/build
.PHONY : rospack_gensrv_all/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-future

# Build rule for target.
test-future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-future
.PHONY : test-future

# fast build rule for target.
test-future/fast:
	$(MAKE) -f CMakeFiles/test-future.dir/build.make CMakeFiles/test-future.dir/build
.PHONY : test-future/fast

#=============================================================================
# Target rules for targets named test-results

# Build rule for target.
test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results
.PHONY : test-results

# fast build rule for target.
test-results/fast:
	$(MAKE) -f CMakeFiles/test-results.dir/build.make CMakeFiles/test-results.dir/build
.PHONY : test-results/fast

#=============================================================================
# Target rules for targets named test-results-run

# Build rule for target.
test-results-run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results-run
.PHONY : test-results-run

# fast build rule for target.
test-results-run/fast:
	$(MAKE) -f CMakeFiles/test-results-run.dir/build.make CMakeFiles/test-results-run.dir/build
.PHONY : test-results-run/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

# target to build an object file
nodes/IndividualMarkersCamera.o:
	$(MAKE) -f CMakeFiles/marker_node_camera.dir/build.make CMakeFiles/marker_node_camera.dir/nodes/IndividualMarkersCamera.o
.PHONY : nodes/IndividualMarkersCamera.o

# target to preprocess a source file
nodes/IndividualMarkersCamera.i:
	$(MAKE) -f CMakeFiles/marker_node_camera.dir/build.make CMakeFiles/marker_node_camera.dir/nodes/IndividualMarkersCamera.i
.PHONY : nodes/IndividualMarkersCamera.i

# target to generate assembly for a file
nodes/IndividualMarkersCamera.s:
	$(MAKE) -f CMakeFiles/marker_node_camera.dir/build.make CMakeFiles/marker_node_camera.dir/nodes/IndividualMarkersCamera.s
.PHONY : nodes/IndividualMarkersCamera.s

# target to build an object file
nodes/IndividualMarkersNoKinect.o:
	$(MAKE) -f CMakeFiles/marker_node_no_depth.dir/build.make CMakeFiles/marker_node_no_depth.dir/nodes/IndividualMarkersNoKinect.o
.PHONY : nodes/IndividualMarkersNoKinect.o

# target to preprocess a source file
nodes/IndividualMarkersNoKinect.i:
	$(MAKE) -f CMakeFiles/marker_node_no_depth.dir/build.make CMakeFiles/marker_node_no_depth.dir/nodes/IndividualMarkersNoKinect.i
.PHONY : nodes/IndividualMarkersNoKinect.i

# target to generate assembly for a file
nodes/IndividualMarkersNoKinect.s:
	$(MAKE) -f CMakeFiles/marker_node_no_depth.dir/build.make CMakeFiles/marker_node_no_depth.dir/nodes/IndividualMarkersNoKinect.s
.PHONY : nodes/IndividualMarkersNoKinect.s

# target to build an object file
nodes/IndividualMarkersService.o:
	$(MAKE) -f CMakeFiles/marker_service.dir/build.make CMakeFiles/marker_service.dir/nodes/IndividualMarkersService.o
.PHONY : nodes/IndividualMarkersService.o

# target to preprocess a source file
nodes/IndividualMarkersService.i:
	$(MAKE) -f CMakeFiles/marker_service.dir/build.make CMakeFiles/marker_service.dir/nodes/IndividualMarkersService.i
.PHONY : nodes/IndividualMarkersService.i

# target to generate assembly for a file
nodes/IndividualMarkersService.s:
	$(MAKE) -f CMakeFiles/marker_service.dir/build.make CMakeFiles/marker_service.dir/nodes/IndividualMarkersService.s
.PHONY : nodes/IndividualMarkersService.s

# target to build an object file
nodes/IndividualMarkersServiceCamera.o:
	$(MAKE) -f CMakeFiles/marker_image_service.dir/build.make CMakeFiles/marker_image_service.dir/nodes/IndividualMarkersServiceCamera.o
.PHONY : nodes/IndividualMarkersServiceCamera.o

# target to preprocess a source file
nodes/IndividualMarkersServiceCamera.i:
	$(MAKE) -f CMakeFiles/marker_image_service.dir/build.make CMakeFiles/marker_image_service.dir/nodes/IndividualMarkersServiceCamera.i
.PHONY : nodes/IndividualMarkersServiceCamera.i

# target to generate assembly for a file
nodes/IndividualMarkersServiceCamera.s:
	$(MAKE) -f CMakeFiles/marker_image_service.dir/build.make CMakeFiles/marker_image_service.dir/nodes/IndividualMarkersServiceCamera.s
.PHONY : nodes/IndividualMarkersServiceCamera.s

# target to build an object file
nodes/IndividualMarkersTopic.o:
	$(MAKE) -f CMakeFiles/marker_node.dir/build.make CMakeFiles/marker_node.dir/nodes/IndividualMarkersTopic.o
.PHONY : nodes/IndividualMarkersTopic.o

# target to preprocess a source file
nodes/IndividualMarkersTopic.i:
	$(MAKE) -f CMakeFiles/marker_node.dir/build.make CMakeFiles/marker_node.dir/nodes/IndividualMarkersTopic.i
.PHONY : nodes/IndividualMarkersTopic.i

# target to generate assembly for a file
nodes/IndividualMarkersTopic.s:
	$(MAKE) -f CMakeFiles/marker_node.dir/build.make CMakeFiles/marker_node.dir/nodes/IndividualMarkersTopic.s
.PHONY : nodes/IndividualMarkersTopic.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ROSBUILD_genmsg_cpp"
	@echo "... ROSBUILD_genmsg_lisp"
	@echo "... ROSBUILD_gensrv_cpp"
	@echo "... ROSBUILD_gensrv_lisp"
	@echo "... ROSBUILD_gensrv_py"
	@echo "... clean-test-results"
	@echo "... edit_cache"
	@echo "... marker_image_service"
	@echo "... marker_node"
	@echo "... marker_node_camera"
	@echo "... marker_node_no_depth"
	@echo "... marker_service"
	@echo "... rebuild_cache"
	@echo "... rosbuild_precompile"
	@echo "... rosbuild_premsgsrvgen"
	@echo "... rospack_genmsg"
	@echo "... rospack_genmsg_libexe"
	@echo "... rospack_gensrv"
	@echo "... rospack_gensrv_all"
	@echo "... test"
	@echo "... test-future"
	@echo "... test-results"
	@echo "... test-results-run"
	@echo "... tests"
	@echo "... nodes/IndividualMarkersCamera.o"
	@echo "... nodes/IndividualMarkersCamera.i"
	@echo "... nodes/IndividualMarkersCamera.s"
	@echo "... nodes/IndividualMarkersNoKinect.o"
	@echo "... nodes/IndividualMarkersNoKinect.i"
	@echo "... nodes/IndividualMarkersNoKinect.s"
	@echo "... nodes/IndividualMarkersService.o"
	@echo "... nodes/IndividualMarkersService.i"
	@echo "... nodes/IndividualMarkersService.s"
	@echo "... nodes/IndividualMarkersServiceCamera.o"
	@echo "... nodes/IndividualMarkersServiceCamera.i"
	@echo "... nodes/IndividualMarkersServiceCamera.s"
	@echo "... nodes/IndividualMarkersTopic.o"
	@echo "... nodes/IndividualMarkersTopic.i"
	@echo "... nodes/IndividualMarkersTopic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

